[WIP] Add xzarr_gdal_store
xtensor-stack/xtensor-zarr pull request #31
Opened 2020-12-29 03:54 UTC by davidbrochart

2020-12-29 04:11 UTC, davidbrochart commented
The OSX failure is because I removed the conda installation of xtensor-io to get https://github.com/xtensor-stack/xtensor-io/pull/133, and removed the linking with the target xtensor-io in the CMake. We can just test on Linux for now, until we get a release of xtensor-io with the GDAL handler.

2021-01-25 13:53 UTC, JohanMabille commented on CMakeLists.txt
> +find_package(zarray 0.0.3 REQUIRED)
I think it could be nice to set the version numbers into variables taht we can reuse in `zarrayConfig.cmake.in` so we have transitive dependencies.

2021-01-25 13:59 UTC, JohanMabille requested changes

2021-01-25 13:59 UTC, JohanMabille commented on include/xtensor-zarr/xzarr_gdal_store.hpp
> +        return std::move(xzarr_gdal_stream(m_root + '/' + key));
You should not use move in a return statement, this may prevents copy elision.

2021-01-25 16:50 UTC, JohanMabille approved these changes

2021-01-25 16:51 UTC, merged